// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShoppingApp.Services.ProductAPI.Data;

#nullable disable

namespace ShoppingApp.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0-rc.2.24474.1");

            modelBuilder.Entity("ShoppingApp.Services.ProductAPI.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("OriginalPrice")
                        .HasColumnType("REAL");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.Property<int?>("Reviews")
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Fashion",
                            Description = "Black Bella Canvas, T-Shirt, Male Model, Lifestyle Outdoor.",
                            DetailedDescription = "Black Bella Canvas, T-Shirt, Male Model, Lifestyle Outdoor. Material: 100% Cotton, Size: L.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "T-Shirt",
                            OriginalPrice = 39.0,
                            Price = 19.0,
                            Reviews = 13
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Fashion",
                            Description = "Blue, 100% cotton drill, 5 pockets.",
                            DetailedDescription = "Blue, 100% cotton drill, 5 pockets. Material: 100% Cotton, Size: M.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Blue Drill Jeans",
                            OriginalPrice = 150.0,
                            Price = 118.0,
                            Reviews = 26
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Accessories",
                            Description = "Genuine Leather, nice looking accessory.",
                            DetailedDescription = "Genuine Leather, nice looking accessory. Material: Genuine Leather, Size: Adjustable.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Leather Arm Band",
                            OriginalPrice = 45.0,
                            Price = 23.0,
                            Reviews = 18
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Fashion",
                            Description = "Comfortable, stylish hoodie with a kangaroo pocket.",
                            DetailedDescription = "Comfortable, stylish hoodie with a kangaroo pocket.Material: 80% Cotton, 20% Polyester, Size: M.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Red Hoodie",
                            OriginalPrice = 50.0,
                            Price = 30.0,
                            Reviews = 12
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryName = "Footwear",
                            Description = "Classic white sneakers for everyday use.",
                            DetailedDescription = "Classic white sneakers for everyday use. Material: Synthetic Leather, Size: 42.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "White Sneakers",
                            OriginalPrice = 100.0,
                            Price = 75.0,
                            Reviews = 17
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryName = "Fashion",
                            Description = "Stylish black leather jacket with zipper pockets.",
                            DetailedDescription = "Stylish black leather jacket with zipper pockets. Material: Genuine Leather, Size: L.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Black Leather Jacket",
                            OriginalPrice = 200.0,
                            Price = 150.0,
                            Reviews = 5
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryName = "Fashion",
                            Description = "Stylish black leather jacket with zipper pockets.",
                            DetailedDescription = "Stylish black leather jacket with zipper pockets. Material: Genuine Leather, Size: L.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Black Leather Jacket",
                            OriginalPrice = 200.0,
                            Price = 150.0,
                            Reviews = 5
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryName = "Fashion",
                            Description = "Casual blue baseball cap with adjustable strap.",
                            DetailedDescription = "Casual blue baseball cap with adjustable strap. Material: 100% Cotton, One size fits all.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Blue Baseball Cap",
                            OriginalPrice = 20.0,
                            Price = 12.0,
                            Reviews = 35
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryName = "Fashion",
                            Description = "Comfortable grey sweatpants with drawstring waist.",
                            DetailedDescription = "Comfortable grey sweatpants with drawstring waist. Material: 60% Cotton, 40% Polyester, Size: M.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Grey Sweatpants",
                            OriginalPrice = 35.0,
                            Price = 25.0,
                            Reviews = 3
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryName = "Footwear",
                            Description = "Elegant black dress shoes for formal occasions.",
                            DetailedDescription = "Elegant black dress shoes for formal occasions. Material: Genuine Leather, Size: 44.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Black Dress Shoes",
                            OriginalPrice = 120.0,
                            Price = 80.0,
                            Reviews = 67
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryName = "Fashion",
                            Description = "Classic white dress shirt for office wear.",
                            DetailedDescription = "Classic white dress shirt for office wear. Material: 100% Cotton, Size: L.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "White Dress Shirt",
                            OriginalPrice = 50.0,
                            Price = 35.0,
                            Reviews = 21
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryName = "Accessories",
                            Description = "Durable black backpack with multiple compartments.",
                            DetailedDescription = "Durable black backpack with multiple compartments. Material: Nylon, Capacity: 20L.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Black Backpack",
                            OriginalPrice = 60.0,
                            Price = 40.0,
                            Reviews = 75
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryName = "Fashion",
                            Description = "Warm grey beanie for cold weather.",
                            DetailedDescription = "Warm grey beanie for cold weather. Material: Wool Blend, One size fits all.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Grey Beanie",
                            OriginalPrice = 25.0,
                            Price = 15.0,
                            Reviews = 18
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryName = "Accessories",
                            Description = "Classic black belt with silver buckle.",
                            DetailedDescription = "Classic black belt with silver buckle. Material: Genuine Leather, Size: 34.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Black Belt",
                            OriginalPrice = 30.0,
                            Price = 20.0,
                            Reviews = 39
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryName = "Accessories",
                            Description = "Brown leather belt with a steel buckle.",
                            DetailedDescription = "Brown leather belt with a steel buckle.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Leather Belt",
                            OriginalPrice = 55.0,
                            Price = 35.0,
                            Reviews = 17
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryName = "Accessories",
                            Description = "Genuine leather wallet with multiple compartments.",
                            DetailedDescription = "Genuine leather wallet with multiple compartments.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Leather Wallet",
                            OriginalPrice = 100.0,
                            Price = 65.0,
                            Reviews = 75
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryName = "Watches",
                            Description = "Waterproof digital watch with multiple functions.",
                            DetailedDescription = "Waterproof digital watch with multiple functions.",
                            ImageUrl = "https://via.placeholder.com/150",
                            Name = "Digital Watch",
                            OriginalPrice = 100.0,
                            Price = 65.0,
                            Reviews = 39
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
